### ISSUE TITLE
log spam

### ISSUE THREAD

**Issue by AnAwesomGuy** [Ecdcaeb/Redirector#12]
there is no way to turn `RedirectionorTransformer#isDeBug` to false, and it causes log spam and lag due to logging through sout

**Comment by Ecdcaeb** [comment]
Yes, I forget it.

**Comment by Ecdcaeb** [comment]
https://github.com/MCTeamPotato/Redirector/releases/tag/1.3_for_1.12.2-1.8.8

**Comment by AnAwesomGuy** [comment]
could you also fix it for 1.7?

**Comment by Ecdcaeb** [comment]
I am sorry but you have to build it youself.
https://github.com/MCTeamPotato/Redirector/actions

**Comment by Ecdcaeb** [comment]
https://github.com/MCTeamPotato/Redirector/releases/tag/1.7.10-1.7
