### ISSUE TITLE
Game load crash

### ISSUE THREAD

**Issue by al-wei** [Ecdcaeb/Redirector#13]
redirectionor-1.12.2-1.8.8-1.2  >>> redirectionor-1.3 for 1.12.2-1.8.8

Update redirectionor crashes.

[log](https://gist.github.com/al-wei/7be9efe62e14443bd948397f83beed03)

**Comment by Ecdcaeb** [comment]
Crash？ The log looks like a normal running.

**Comment by Ecdcaeb** [comment]
Need more information. It looks do not like a full log. Something was stuck or stop immediatelly.
Relate to #9 ? Idk. Need futher test and more information.

**Comment by al-wei** [comment]
> Need more information. It looks do not like a full log. Something was stuck or stop immediatelly. Relate to #9 ? Idk. Need futher test and more information.

![image](https://github.com/Ecdcaeb/Redirector/assets/145486869/138f6cf0-40c4-47d4-9c30-dcedb1b3aa71)

**Comment by al-wei** [comment]
[debug.log](https://github.com/Ecdcaeb/Redirector/files/14971146/debug.log)
[latest.log](https://github.com/Ecdcaeb/Redirector/files/14971147/latest.log)

**Comment by al-wei** [comment]
These are the only files
[crash-2024-04-14_22.53.13-client.txt](https://github.com/Ecdcaeb/Redirector/files/14971152/crash-2024-04-14_22.53.13-client.txt)

**Comment by AnAwesomGuy** [comment]
blacklist `com/github/benmanes/caffeine/cache/BoundedLocalCache`

**Comment by Ecdcaeb** [comment]
`redirectionor.cfg` write like this:
```
{ 
"printTransformedClasses":false,
"type": "block", 
"contains": [ 
    "com.github.benmanes.caffeine.cache.BoundedLocalCache" 
   ] 
}
```
