### ISSUE TITLE
printTransformedClasses

### ISSUE THREAD

**Issue by al-wei** [Ecdcaeb/Redirector#14]
printTransformedClasses
这个为什么不能false。改了进游戏又重置了，我感觉开了这个是不是会有些负担，我不想开着。

redirectionor-1.5 for 1.12.2-1.8.8

**Comment by al-wei** [comment]
这还让我的游戏地图加载卡了，无法加载那种，破坏无掉落，区块无生成。
降低到 redirectionor-1.4 for 1.12.2-1.8.8 我的地图就正常了
我给个日志
https://mclo.gs/CTJ2JEe

**Comment by Ecdcaeb** [comment]
> printTransformedClasses 这个为什么不能false。改了进游戏又重置了，我感觉开了这个是不是会有些负担，我不想开着。
> 
> redirectionor-1.5 for 1.12.2-1.8.8
关于printClass，非常抱歉这里范了个非常傻的错误：
https://github.com/Ecdcaeb/Redirector/blob/1.12.2-1.8.8/src/main/java/com/Hileb/teampotato.redirectionor/RedirectionorConfig.java#L69

**Comment by Ecdcaeb** [comment]
https://github.com/MCTeamPotato/Redirector/releases/tag/1.12.2-1.8.8-1.6

curseforge的更新稍后。

**Comment by al-wei** [comment]
> https://github.com/MCTeamPotato/Redirector/releases/tag/1.12.2-1.8.8-1.6
> 
> curseforge的更新稍后。

1.5 版本可以把它存档了，以免有人遇到，卡死情况

**Comment by al-wei** [comment]
> https://github.com/MCTeamPotato/Redirector/releases/tag/1.12.2-1.8.8-1.6
> 
> curseforge的更新稍后。

真的测试过吗？就只加载这个都崩溃。
https://mclo.gs/m8YXlTI

**Comment by al-wei** [comment]
> > https://github.com/MCTeamPotato/Redirector/releases/tag/1.12.2-1.8.8-1.6
> > curseforge的更新稍后。
> 
> 真的测试过吗？就只加载这个都崩溃。 https://mclo.gs/m8YXlTI

https://github.com/Ecdcaeb/Redirector/issues/15
老铁又来了。真的会崩溃啊。
