### ISSUE TITLE
Latest version doesn't work

### ISSUE THREAD

**Issue by XvaleX10** [Ecdcaeb/Redirector#15]
[latest.log](https://github.com/user-attachments/files/16962383/latest.log)

**Comment by Yabe-uke** [comment]
Gonna comment the same, crashes previously working instance on boot. Also version 1.5 (wich worked) is gone from Curseforge

**Comment by al-wei** [comment]
> Gonna comment the same, crashes previously working instance on boot. Also version 1.5 (wich worked) is gone from Curseforge

Because version 1.5 also has problems. Version 1.4 can be used for now.

**Comment by owlultra** [comment]
same issue here

**Comment by UnLovedCookie** [comment]
Just wanted to say that I'm having this issue as well, please fix!

**Comment by Yabe-uke** [comment]
As a small addendum I'll reinstate version 1.5 still works for me, both server and client with no issues in sight. If version 1.6 is broken I'd advise taking it down to avoid unnecessary issue spam here.

Edit: my server runs with a custom 319 mod modpack, if you want any logs I'll be happy to help.

**Comment by Ecdcaeb** [comment]
An obvious mistake, forgetting to `apply` when transforming `FMLCommonHandler`.
I am very sorry for making stupid mistakes continuously, I should take a good rest.

https://github.com/MCTeamPotato/Redirector/commit/438b572286efeeb65b9bf80325f576b7e6b1c9f5#diff-ab4a1e41ad62cef8b18cf4d2580d2cf04b835df95c768914617746c0850e5d8b

**Comment by Ecdcaeb** [comment]
1.5, 1.6, and 1.7 are all one updated version in theory.
I tested it under Cleanroom and there should be no problem this time.

**Comment by Yabe-uke** [comment]
> I am very sorry for making stupid mistakes continuously, I should take a good rest.

You're doing god's work my mane, no need to apologise, you're a lifesaver

> I tested it under Cleanroom and there should be no problem this time.

I'm waiting for the team to add support either there or on Fugue for Valkyrien Skies, and my modpack will boot in Cleanroom!
